[project]
name = "mcp-scripts"
version = "0.1.0"
description = "List of scripts for MCP"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=0.4.1",
    "httpx>=0.28.1",
    "python-dotenv>=1.1.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.4",
]
